CC = gcc
CFLAGS = -Wall -Wextra
SRCS = main.c utils.c lista_seq.c lista_enc.c pilha.c fila.c fila_circ.c fila_dupla.c fila_prio.c
OUT = simulador

all:
	$(CC) $(CFLAGS) $(SRCS) -o $(OUT)

clean:
	rm -f $(OUT)
